name = "flying-dutchman-loyalty"

[build]
command = "npm install passkit-generator"

# For Cloudflare Pages Functions
[functions]
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-01-01"